name: Build and Run Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build the Spring Boot Application
        run: mvn clean package

      - name: Show Public IP of the GitHub Runner
        run: curl -s ifconfig.me

      - name: Run Spring Boot Application on Port 1900
        run: |
          nohup java -jar target/*.jar --server.port=1900 &

      - name: Check Running Processes
        run: ps aux | grep java
